# Generated by Django 2.0.5 on 2018-05-31 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('url', models.URLField(blank=True, max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField()),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='accounts.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=125)),
                ('url', models.URLField(blank=True, max_length=125)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myusers', to='accounts.Groups')),
            ],
        ),
        migrations.AddField(
            model_name='ip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='accounts.MyUsers'),
        ),
    ]
