# Generated by Django 2.0.5 on 2018-05-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('url', models.URLField(blank=True, max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=125)),
                ('url', models.URLField(blank=True, max_length=125)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='accounts.Group')),
            ],
        ),
    ]
