# Generated by Django 2.0.5 on 2018-06-01 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=125)),
                ('content', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.MyUsers')),
            ],
        ),
    ]
