# Generated by Django 2.0.5 on 2018-06-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180612_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='interestGroups',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='accounts.InterestGroup', verbose_name='Member interestGroup'),
        ),
    ]
